### ISSUE TITLE
Save tabs to disk

### ISSUE THREAD

**Issue by ctf0** [usama8800/VSCode-Tab-Groups#1]
i think its in session because the moment you close the editor you cant restore any of the saved groups.

if thats the case, it is possible for the plugin to save the open tabs as file paths in a text file that gets saved to the user settings ?

this way you can restore the groups at any time & at any instance of the opened editors.

**Comment by lsdevrp** [comment]
@usama8800 is there any possibility to save on disc the groups?

**Comment by usama8800** [comment]
I'll work on it

**Comment by usama8800** [comment]
https://github.com/usama8800/VSCode-Tab-Groups/commit/d24769755c5441ef9a501dfa7f24b86d658a3057

**Comment by lsdevrp** [comment]
Hey @usama8800, great job!
Now, It is possible to keep on disk and if necessary we can commit the settings.json to the repo 👍 

I'm using this extension to map big flows of monolithic software. Congratulations, thanks!
