### ISSUE TITLE
All extension commands 'not found'.

### ISSUE THREAD

**Issue by Kyamon** [usama8800/VSCode-Tab-Groups#10]
Clicking the save icon in the sidebar results in
![May_29_2020 451 x 43](https://user-images.githubusercontent.com/15200348/83254715-79c95900-a16c-11ea-8288-08503e5c0728.png)
Using any command from palette results in something similar to this
![May_29_2020 451 x 65](https://user-images.githubusercontent.com/15200348/83255064-fe1bdc00-a16c-11ea-892b-e9a815b9f8a7.png)
I tried using an earlier version than with the added sidebar and the commands all work fine.

**Comment by usama8800** [comment]
Is git your VCS?

**Comment by usama8800** [comment]
Could you try this without other extensions?

You can do that by copying the `usama8800.tab-groups-1.3.1` directory in `~/.vscode/extensions` to a new directory and starting vscode like this `code --extensions-dir dir_containing_extension`

**Comment by Kyamon** [comment]
> 
> 
> Is git your VCS?
Didn't realize that git was a separate program/installation. Installing it fixed the problem.
