### ISSUE TITLE
Wish: Setting for vertical/horizontal split

### ISSUE THREAD

**Issue by smukkekim** [usama8800/VSCode-Tab-Groups#11]
In #8 you mention, that because you cannot read split direction, splits will always be vertical when opening a tab set.

99% of the time, I use a horizontal split in my setup.

Would it be possible to add a setting, to choose whether to always use horizontal or vertical splits when opening a set?

**Comment by usama8800** [comment]
You can use the `"workbench.editor.openSideBySideDirection": "down"` setting for that
