### ISSUE TITLE
setting tab-groups.gitBranchGroups stopped working

### ISSUE THREAD

**Issue by smukkekim** [usama8800/VSCode-Tab-Groups#14]
After upgrading to 1.3.3 the setting `"tab-groups.gitBranchGroups": false` is ignored. 
Tab groups now keep updating whenever I switch branch.

**Comment by lonix1** [comment]
`"tab-groups.gitBranchGroups": false` shows an error in vscode. Expected string.

The default is `"Save and Restore"`. What should I use?

**Comment by usama8800** [comment]
If you use autocomplete on the setting it will show you all the valid values. I think if you had false it's "Nothing"

**Comment by lonix1** [comment]
Thanks.

There is "Save and Restore" and "Save only" - I assume the latter is the equivalent of "false".

**Comment by usama8800** [comment]
I just checked. "Nothing" is also an option. It won't save the tabs if you don't want the list cluttered
