### ISSUE TITLE
Closing all tabs / editors within a workspace upon restart 

### ISSUE THREAD

**Issue by semsion** [usama8800/VSCode-Tab-Groups#15]
I've noticed some unexpected behaviour when creating a new tab group.

If I save a new tab group with a given workspace and restart VsCode, upon restart all the tabs / editors are closed.

VsCode: 1.46.0
Ubuntu: 18.04.4

**Comment by usama8800** [comment]
I can't reproduce this. 

VSCode : 1.46.1 (no other extensions, all default settings)
Ubuntu: 18.04.4

Maybe it's one of your settings?

**Comment by itsopen** [comment]
I just tried this again, and it appears that restarting the os after creating the new tab group should display the issue.
