### ISSUE TITLE
Not saving tabs - error

### ISSUE THREAD

**Issue by yairEO** [usama8800/VSCode-Tab-Groups#16]
![image](https://user-images.githubusercontent.com/845031/86745116-cbee7b80-c042-11ea-827b-43344c80a195.png)

```
[usama8800.tab-groups]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api usama8800.tab-groups
```

VSCODE Insiders Build June 2020 v1.47

**Comment by usama8800** [comment]
Does this occur on startup or on a specific command?

**Comment by yairEO** [comment]
it shows the error what I click on the button thats all open tabs

**Comment by bcsingh50** [comment]
Having the same error when I try to expand a tabbed group. Interestingly the tabbed group still opens without issue.

**Comment by usama8800** [comment]
Are you also using VSCode Insiders?

**Comment by bcsingh50** [comment]
Hi im not no (unless its something im not aware of!) Im on Version: 1.47.1

**Comment by fade2gray** [comment]
Latest vscode system install on win10
![TabGroups](https://user-images.githubusercontent.com/1332009/89102058-7fa61980-d3fd-11ea-8e9b-e109360656f2.PNG)

**Comment by usama8800** [comment]
> Latest vscode system install on win10
> ![TabGroups](https://user-images.githubusercontent.com/1332009/89102058-7fa61980-d3fd-11ea-8e9b-e109360656f2.PNG)

This happens when you don't have git installed
