### ISSUE TITLE
Navigate to file from group view

### ISSUE THREAD

**Issue by penguin020** [usama8800/VSCode-Tab-Groups#17]
I would like the extension to open each individual file is clicked in the "Tab Group View" sidebar.

**Comment by LTIOfficial** [comment]
I will 'second' this request.
The resulting convenience would be highly in-line with the purpose of the extension

**Comment by usama8800** [comment]
https://github.com/usama8800/VSCode-Tab-Groups/commit/a82fb6ddde845b06316d42c27d70fe3fc2f93e27 Added this feature
