### ISSUE TITLE
Remember pinned tabs

### ISSUE THREAD

**Issue by xmedeko** [usama8800/VSCode-Tab-Groups#18]
VS Code tab can be pinned now. I would welcome if VSCode-Tab-Groups would remember and restore the pinned state as well.

**Comment by usama8800** [comment]
Pinning tabs is not supported by the API yet https://github.com/usama8800/VSCode-Tab-Groups/issues/13

**Comment by xmedeko** [comment]
It's pity VS Code does dot support it. Thanks for the quick reply.

**Comment by xmedeko** [comment]
But you have implemented it by 86e015b23fecde64139635c7d45a5dba616cc461
Great!
