### ISSUE TITLE
Saving to existing groups with no tabs open

### ISSUE THREAD

**Issue by ibLeDy** [usama8800/VSCode-Tab-Groups#19]
All the previous tabs in the group get replaced with no tab, so you lose all of them if clicked by mistake.

It should at least warn you that you're saving no tabs or something. Take this workflow as an example:

- Save current opened tabs in a new/existing group
- Click `close all editors` button
- Go to a tab group and try to click `restore tab group` button but click `save tab group` by mistake
- All my saved tabs in that group gets replaced

**Comment by usama8800** [comment]
I'm thinking an undo button would be better instead of a warning

**Comment by ibLeDy** [comment]
I think that the undo button is nice in all situations, not only when clicking by mistake, but the warning would prevent the need to even undo.

With that said, any option would solve my issue, so i'm happy because this is the only complaint i have with the extension atm.
