### ISSUE TITLE
Doesn't restore all tabs

### ISSUE THREAD

**Issue by phil4literacy** [usama8800/VSCode-Tab-Groups#2]
I love the idea. This is especially useful if one often has to switch between git branches. However, restore doesn't work. It only restores 2 tabs or so. Maybe it's a Windows issue...

**Comment by usama8800** [comment]
Can you try it out now? Version 1.0.2

**Comment by phil4literacy** [comment]
Thanks for getting back to me. I now think I've found the problem. It seems to not work together with the extension "stack-tabs" https://github.com/kylepaulsen/vscode-stack-tabs. After I disabled it, it seemed to work.
