### ISSUE TITLE
Quick Restore and Auto Save feature?

### ISSUE THREAD

**Issue by agquick** [usama8800/VSCode-Tab-Groups#20]
Hi,

First off - thanks so much for this extension, It's super helpful. A few quick questions:

1. Is it possible to add a quicker restore functionality? Maybe double-click on the tab group name? It would make switching groups much simpler for me than aiming for the little restore button.
2. Is there a way to have the tab groups auto-save? So that it would keep the state of the group as I open and close files?

Thanks again!

**Comment by usama8800** [comment]
I added the quick restore functionality. I also tried the auto-save thing but I'm not satisfied with it. I couldn't update the tabs as you changed them. Check the last paragraph in the usage section of the readme. Maybe try it out and lemme know.

**Comment by agquick** [comment]
That's awesome, I'll check it out and let you know. Thanks for taking the time on this!
