### ISSUE TITLE
Do not save splitted tabs

### ISSUE THREAD

**Issue by venoel** [usama8800/VSCode-Tab-Groups#22]
I have open tabs in three groups.

When I try to save opened tabs in "Tab groups" they are saving only in one or two splits.
And when I open this group - files are opened in two columns.
![Виділення_999(009)](https://user-images.githubusercontent.com/15649006/109393720-1901c380-792c-11eb-8aac-a2cdf5754b2a.png)
Her should be "Split 3", but it is not.

**Comment by usama8800** [comment]
Can you also show what it is opening and what it's supposed to open?

**Comment by venoel** [comment]
There are **three** splits before saving the tabs .
![Виділення_999(010)](https://user-images.githubusercontent.com/15649006/109394269-d7264c80-792e-11eb-8709-a0923749cfc7.png)

Third group are lost immediately after saving.
![Виділення_999(011)](https://user-images.githubusercontent.com/15649006/109394232-a514ea80-792e-11eb-9377-8d7d4eeb8567.png)
And there are only **two** splits
![Виділення_999(012)](https://user-images.githubusercontent.com/15649006/109394246-b0681600-792e-11eb-8d42-109f3a258bcb.png)

Count of files are saved correctly.

**Comment by venoel** [comment]
One or two weeks ago three groups was saved correctly. And restored as three columns, not rows, but that was not the problem.

**Comment by usama8800** [comment]
I'll take a look. I did change how they're saved to support pinned tabs so maybe it broke
