### ISSUE TITLE
[Feature Request] Do not restore groups after changing git branch

### ISSUE THREAD

**Issue by lonix1** [usama8800/VSCode-Tab-Groups#23]
The `tab-groups.gitBranchGroups` feature is really nice!

But it both saves AND restores. When switching branches, sometimes my vscode goes crazy, opening tabs, closing them, opening, closing, again, again. And then... the wrong ones are open. :smile: 

Please add a feature so we can save automatically, BUT not restore (this can be done manually from the sidebar).

Perhaps `"tab-groups.automaticRestoreOnGitBranchChange": true` - this would make it a backward-compatible change. And if you want to disable that behavior, you set that to `false`.

**Comment by usama8800** [comment]
Good idea
