### ISSUE TITLE
Broken Icon on Hover Over Tab Group with Latest Version of VS Code (v1.56.0)

### ISSUE THREAD

**Issue by SolarTheory** [usama8800/VSCode-Tab-Groups#24]
The latest version of VS Code (v.1.56.0) seems to have broken the icons that show up when you hover over a tab group.  Upon reverting to a previous version of VS code, the issue went away.  Not sure if this is something that you need to fix on your end or if it's a VS Code bug, but I thought you should be aware:  

Broken Icons Image:
![Tab Groups-Broken-Icon-On-Hover-Over-Group-Dark-Theme-VSCv1 56](https://user-images.githubusercontent.com/15674476/117230293-c42a6f80-adea-11eb-93a5-dbca6da0cf20.png)

VS Code Version
![VS Code Version 1 56 0](https://user-images.githubusercontent.com/15674476/117230341-e15f3e00-adea-11eb-86fe-1d3dfbb2625c.png)
:

**Comment by usama8800** [comment]
I did see this bug in other extensions too
