### ISSUE TITLE
Closed most of my tabs, didn't save

### ISSUE THREAD

**Issue by codebykat** [usama8800/VSCode-Tab-Groups#28]
I installed this extension with a lot of tabs open (the problem).

I opened the sidebar and pressed "Save current tabs". I gave it a name and pressed enter.

It freaked out and flashed a bunch, slowly managing to close 90% of my tabs. When it finally stopped, it had simply closed all but three tabs, but apparently didn't save them anywhere. Very frustrating. I mean I guess my problem is technically "solved" but not in the way I hoped.

VS Code Version: 1.56.2 on OSX Catalina.

**Comment by usama8800** [comment]
How is your problem solved?

Also can you show a screenshot of the layout of your tabs which don't save

**Comment by codebykat** [comment]
Sorry, I missed this reply. My problem was "solved" in that I no longer had too many open tabs to manage, because the extension closed them all. I don't know why it failed the way that it did. I don't have a screenshot because it closed all my tabs the first time I tried to use it without putting them anywhere. The screenshot would just be my VS Code with three tabs open where it used to have around 50.

I realize that's not at all helpful for debugging, but it was a very frustrating experience and I wanted to let you know. I immediately removed the extension because losing my data is a dealbreaker.

If no one else has reported this issue feel free to close it. If you'd like me to check somewhere for an error log I would be happy to do that as well.
