### ISSUE TITLE
Update existing tab group

### ISSUE THREAD

**Issue by duke79** [usama8800/VSCode-Tab-Groups#3]
Ability to save/merge the updated list of tabs one of the existing tab groups.

**Comment by usama8800** [comment]
Can you be more clear? I don't understand very well what you mean.

**Comment by duke79** [comment]
When I already have a tab group with some files -
```
file1
file2
```
I save it as TabGroup1.
Then I open some more files -
```
file1
file2
file3
```
I want to update the TabGroup1 to have all the files currently opened, by choosing it from a dropdown, instead of having to type TabGroup1 again (which also results in an issue, if I use save command with the same name TabGroup1, then if I try to restore there are going to be two entries for TabGroup1 in the list).
