### ISSUE TITLE
[Bug] Does not restore tabs in their original order

### ISSUE THREAD

**Issue by lonix1** [usama8800/VSCode-Tab-Groups#30]
vscode: 1.58.0
extension: 1.4.8

When restoring tabs, it restores them in random order, rather than their original order.

Otherwise, very useful extension... thanks!

**Comment by jasonferrier** [comment]
I am experiencing this issue as well.

**Visual Studio Code**
```
Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:56:36.444Z (1 wk ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0
```

**Extension**
v1.4.8

**Comment by gecko9** [comment]
Same problem here too. This is a much needed extension, thank you. It would be very good if this were fixed.

Version: 1.62.2 (user setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

Name: Tab Groups
Version: 1.4.8
Publisher: Usama Ahsan

**Comment by lonix1** [comment]
@usama8800 Does the new tabs API help in this problem?

**Comment by usama8800** [comment]
@lonix1 I didn't know about it. I'll check it out
