### ISSUE TITLE
sub-tab-group

### ISSUE THREAD

**Issue by teymoork** [usama8800/VSCode-Tab-Groups#31]
Is it possible to create a sub-tab group?  If no what does the "Split 1" means  in the attached screen shot:

![to-github](https://user-images.githubusercontent.com/36455783/130444738-70145b8d-4fe0-49af-83fd-61882f31c9be.PNG)

**Comment by usama8800** [comment]
These are editor groups. So in the picture below, there would be 3 splits ![](https://code.visualstudio.com/assets/docs/getstarted/userinterface/sidebyside.png)

**Comment by teymoork** [comment]
Hi Usama, and thanks for your prompt reply. 😎

1-Do you mean that each split can have its own tab group?
2- Should I install this nice extension for every new window or new
workplace in vscode? it seems so for me.

Thanks again

Best Regards
Teymoor

**Comment by usama8800** [comment]
1. Each split (editor group) will be saved in one Tab Group so in your picture, there will be a `Split 1`, a `Split 2`, and a `Split 3` each with only the files in that editor group looking something like this
````
- Group 1
     - Split 1
         - host.contribution.ts
         - extHostApiCommands.ts
     - Split 2
         - buildfile.js
         - workbench.main.css
     - Split 3
         - issue_template.md
````
2. You don't need to install extensions per workspace or window. An extension by default is enabled on all windows unless disabled specifically for a workspace

**Comment by teymoork** [comment]
Great!

 I'm implementing different UML_sequence diagrams which each time
involves a different set of source files.
It would be very convenient to be able to change the name of the
file-sets/tabs from split 1, split 2,.... to  seq 1, seq 2,....
or any other arbitrary but relevant group names. Is it possible today?

My Regards
Teymoor

**Comment by usama8800** [comment]
For that you can save a tab group per set of files like you named in this picture
> ![to-github](https://user-images.githubusercontent.com/36455783/130444738-70145b8d-4fe0-49af-83fd-61882f31c9be.PNG)

**Comment by teymoork** [comment]
what i mean, is the ability of grouping a set of tabs (tab=set of files)
under a "level-2 or supper tab" . This can be very useful
in big projects when you have to deal with different sub and sub-sub
projects/repositories simultaneously from ONE
monitoring center. 😎
