### ISSUE TITLE
Unclear on how to associate tag groups with git branches

### ISSUE THREAD

**Issue by cori** [usama8800/VSCode-Tab-Groups#32]
I'm probably just missing something, but I have a couple of tag groups named with a git branch name and they don't restore when switching branches. I've tried switching within VS Code and also in the terminal, and tab groups never restore.

I named couple of tab groups with `Branch: %branchname`, so maybe I'm just not clear on how to get a tab group linked to a git branch.

Any help would be appreciated!

**Comment by usama8800** [comment]
You don't name branch tab groups although you can but be careful in naming them exactly. There is a setting `tab-groups.gitBranchGroups` which you can set to `"Save and Restore"` and it should automatically create a tab group which you change branches and automatically restore them

**Comment by cori** [comment]
That makes sense, but the reason I tried naming a group that way is because even with the setting set to save and restore new groups seem not to be created. 

Do I have to switch branches in some specific way?
