### ISSUE TITLE
a couple of questions

### ISSUE THREAD

**Issue by ctf0** [usama8800/VSCode-Tab-Groups#4]
- can we have an option to either save the tab groups global or in workspace
- can we save the editor layout as well when saving the tabs ?

**PS:**
atm u save the doc full data to the settings, not sure why but i believe the doc filename is enough.

**Comment by usama8800** [comment]
I added the global setting and I encoded the groups list so it doesn't take too much space in the settings file. 

I don't think we can save the editor layout
