### ISSUE TITLE
Can't delete more than 1 saved tab

### ISSUE THREAD

**Issue by GuillaumeAmat** [usama8800/VSCode-Tab-Groups#41]
Hey :wave: 

I stumbled uppon an issue when deleting tabs:

1. Open teh `TAB GROUPS: TAB GROUPS" section in the `EXPLORER` panel
2. Expand a saved session
3. Hover over a file/tab name
4. Click on the "cross" button to delete it from the saved session (:heavy_check_mark:)
5. Click again on the "cross" button to delete another tab (:boom:)

At the second attempt, the tab remains in the list, and the following notification is displayed:

![image](https://user-images.githubusercontent.com/1179174/178300518-a723cd5e-e167-4d4c-a778-1b0e6d9ea7f0.png)

**Comment by usama8800** [comment]
Is it possible this tab group was saved before the latest version?

**Comment by GuillaumeAmat** [comment]
Unfortunately, I tried with both old groups and a brand new one, created on purpose.

**Comment by GuillaumeAmat** [comment]
Without any other extension and no settings at all, I still have the exact same issue :/

![image](https://user-images.githubusercontent.com/1179174/179401524-d16f8a2f-70f7-4131-8a01-28db3fb559fe.png)
