### ISSUE TITLE
Doing a git rebase when having tabs linked to branches closes all tabs

### ISSUE THREAD

**Issue by ianloic** [usama8800/VSCode-Tab-Groups#42]
I'm using `"tab-groups.gitBranchGroups": "Save and Restore"`which is *amazing*, but when I do a `git rebase -i` (as I often do to maintain a stack of changes) while I'm in the rebasing detached state if I focus my VSCode window all of my tabs close. I assume this is because my HEAD no longer points to the named branch I was editing.

It would be nice if Tab Groups only tried to restore tabs when I switch to a new named branch, either as an option or by default.

I've only just started using Tab Groups, but I think the behavior I'd probably want more generally is to only replace my tabs when I switch to a branch where I've previously saved a set of tabs. That way if I create a new branch my tabs stay open but as I close them or open new ones that set of tabs is saved to the new branch name.

**Comment by usama8800** [comment]
That's a great feature. I'll add it soon
