### ISSUE TITLE
Unable to find extension on VS Code Extensions Marketplace?

### ISSUE THREAD

**Issue by davidleejy** [usama8800/VSCode-Tab-Groups#49]
Hi, anyone facing the same problem?

![Screenshot 2022-10-21 at 1 18 02 AM](https://user-images.githubusercontent.com/1690072/197016366-08c50361-0d41-42ff-8b37-95d4a79ed5fd.png)

Also tried searching with the phrase "Tab Groups" to no avail.

**Comment by usama8800** [comment]
Have you tried restarting VSCode? If that also doesn't work, go to the [marketplace](https://marketplace.visualstudio.com/items?itemName=usama8800.tab-groups) website and click install there
