### ISSUE TITLE
Can't use the commands - it's returnig *not found*

### ISSUE THREAD

**Issue by lsdevrp** [usama8800/VSCode-Tab-Groups#5]
After updating to the last version, 1.0.5, I can't use the commands. It's always returning *not found*.
I restored the version 1.0.2 and it's working well.

1.0.5
![tab-groups-1-0-5](https://user-images.githubusercontent.com/27583560/71604607-e4388780-2b41-11ea-8c45-a00555ec4d8d.gif)

1.0.2
![tab-groups-1-0-2](https://user-images.githubusercontent.com/27583560/71604613-ebf82c00-2b41-11ea-9523-e41c66de36a6.gif)

**Comment by usama8800** [comment]
Looks like it was crashing in a constructor. I fixed it
