### ISSUE TITLE
Backup Tab Groups

### ISSUE THREAD

**Issue by adithyabsk** [usama8800/VSCode-Tab-Groups#63]
I was looking through the source code and it looks like the TabGroups themselves are saved in base64 form `workspace` or `global` storage depending on the setting. How would I go about backing up these Tab Groups

**Comment by usama8800** [comment]
Copy the base64 string where ever you want? It should be in a JSON file. You can search where the file is located based on your settings

**Comment by adithyabsk** [comment]
@usama8800 is there an easy way to determine the current path of the storage file? I'm looking through my file system and notice many different folders with hex strings, I assume representing different workspaces that I've opened over time.

**Comment by usama8800** [comment]
For globalStorage it's in `~/.vscode/User/globalStorage/state.vscdb`
For workspaceStorage it's in `~/.vscode/User/workspaceStorage/<workspace_id>/state.vscdb`

These are SQlite3 files

To get workspace id, open developer tools of vscode (Help > Developer Tools) and in the console do this one line at a time
```
config = await vscode.context.resolveConfiguration()
config.workspace.id
```

You can use https://inloop.github.io/sqlite-viewer/ to open the file and the key is `usama8800.tab-groups`

**Comment by adithyabsk** [comment]
@usama8800 yep, that's where it was. Would really appreciate a way to backup and restore a json file or something similar so that we can reload the saved tab groups on a different machine.

Here's [a stack exchange answer](https://stackoverflow.com/a/72851837) with all of the variations of the locations the file could exist. I used the following to dump the contents:

```sql
select * from ItemTable where key='usama8800.tab-groups';
```

**Comment by adithyabsk** [comment]
For context, if you need to modify the paths you need to do the following:

1. Decode the data from base64
2. Modify the paths
3. Rencode to base64
4. Encode to hex so that it can be re-inserted as a blob in the sqlite DB

^ that's a bit a complicated, so a native way would be preferable
