### ISSUE TITLE
Feature Request: Tabs saved on branch change

### ISSUE THREAD

**Issue by Jared-Dev** [usama8800/VSCode-Tab-Groups#7]
# Feature Request 
I would love to see is to automate this plugin a bit in regards to its functionality surrounding `git` branches.

Ideally this would look something like...

### When leaving a branch
1. If you have five tabs open
2. You switch branches
3. Open tabs are all saved (bonus points if the groups/layout could be saved)
3. Have a setting that designates if all tabs should close or stay open. I see two options ATM, Close All, Leave All Open _(if you are switching to a branch that was previously saved the tabs should close and open the previous group)_

### When loading a branch
1. Checks for existing branches with saved tabs.
2. If the branch has saved tabs -> Open them all

**Comment by usama8800** [comment]
That's an awesome idea!
I'll try to implement it but no bonus points are possible currently, unfortunately

**Comment by usama8800** [comment]
Blocked on [https://github.com/microsoft/vscode/issues/97113](this issue)

**Comment by usama8800** [comment]
I just published a change. I changed the extension to activate on startup until the issue is fixed
