### ISSUE TITLE
Save layout and order

### ISSUE THREAD

**Issue by gilesbutler** [usama8800/VSCode-Tab-Groups#8]
Hey @usama8800,

Awesome extension and thanks for releasing this 👍

Is it possible for the extension to remember the tab layouts both in terms of:
1. Tab order
2. Split editor layout

I often work in a split vertical screen with presentational components in the left tabs and logical components in the right. It would be amazing if this extension could remember the split and which order the tabs were in :) 

Thanks

**Comment by usama8800** [comment]
I pushed a commit. I couldn't find anything that would give me the real tab order. When you restore a tab group, the first one will be your focused editor when you saved. Also, I could only save the tabs in different splits, not where the splits are. So if you had horizontal and vertical splits, when you restore you will only have verticle splits but you can drag them around.

**Comment by gilesbutler** [comment]
Hey @usama8800 that's awesome, thanks so much!

I only use vertical splits so it works really well 🙂
